# Site Settings
title: Sapucaia.Tech | Comunidade de tecnologia de Montes Claros (MG)
url: "https://sapucaia.tech"
collections:
  posts:
    output: true
    permalink: /:collection/:title

# Social
telegram: "https://t.me/sapucaiatech"
github: "https://github.com/sapucaiatech"
youtube: "https://www.youtube.com/channel/UCaKqU9gsKgeaOshOwkvIIXA/videos"
facebook: "https://www.facebook.com/sapucaia.tech/"

# Build settings
markdown: kramdown

# Gems
gems:
  - jekyll-seo-tag

sass:
  sass_dir: _sass
  style: compressed
